// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD5vueTyHOTqIXdRX-b54J9xhafqv6sw5o',
    appId: '1:303897577491:web:73b0c8ea25f8b46a5397e6',
    messagingSenderId: '303897577491',
    projectId: 'smart-ledger-7bbf9',
    authDomain: 'smart-ledger-7bbf9.firebaseapp.com',
    storageBucket: 'smart-ledger-7bbf9.firebasestorage.app',
    measurementId: 'G-YWDK3ZHFEG',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBMa6zK_KjWP6Gu-HeLTCeEohAcQvWLfkg',
    appId: '1:303897577491:android:8f93a0e0da50f49a5397e6',
    messagingSenderId: '303897577491',
    projectId: 'smart-ledger-7bbf9',
    storageBucket: 'smart-ledger-7bbf9.firebasestorage.app',
  );
}
